version: '2'
services:
  appserver:
    build:
      dockerfile: docker/Dockerfile-django
      context: .
      
  webserver:
    build:
      dockerfile: Dockerfile-nginx
      context: docker
    ports:
      - "9080:80"
    depends_on:
      - appserver